services:
  discord-bot:
    build: .
    container_name: mythicmate-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONUNBUFFERED=1
    volumes:
      - mythicmate_data:/usr/src/app/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mythicmate_data:
    name: mythicmate_data
