name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      IMAGE_NAME: mp
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag the Docker image
        run: |
          TIMESTAMP=$(date +%s)
          IMAGE_TAG="${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TIMESTAMP}"
          LATEST_TAG="${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"

          echo "Building image $IMAGE_TAG"
          docker build . \
            --file Dockerfile \
            --tag "$IMAGE_TAG"

          echo "Tagging image as latest"
          docker tag "$IMAGE_TAG" "$LATEST_TAG"

      - name: Push Docker image to Docker Hub
        run: |
          docker push "${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TIMESTAMP}"
          docker push "${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
